### ISSUE TITLE
Feature Request : Ability to dynamically add custom class to the tag 

### ISSUE THREAD

**Issue by dipeshparashar** [smhaley/react-text-annotate-blend#8]
I would like to animate the highlighted text in various ways. It will be great if you can add the ability to add custom classNames to a specific tag. This can be achieved by adding an attribute  like this :

```
{
    "start": 24,
    "end": 41,
    "text": "blend annotations",
    "tag": "tagB",
    "color": "#42f5f5",
    "customClasses": "myCustomClass ",

  }
```

The customClasses attribute above. 
Please let me know if this can be achieved anytime soon. 
Thank you.

**Comment by smhaley** [comment]
I'm not sure how this could be implemented with the blended portion of tags.

This is a reasonable request for non blended tags as they are predictable. However the blended portion of the tag is uncontrolled by the component. In other words, the total number of combinations of  the blended portion is very large. I believe it would something like:
 <pre><sub>n</sub>C<sub>2</sub> +  n* 2 </pre>
 total combinations where `n` is the total number of tag options ( multiplied twice because the color does change when tagging with the same tag twice).

This is a lot of tags. For example, if there were just 3 options, then there would be 6 total combinations to track. 

Anyway, there could be a simple lookup for all controlled (or named tags/classes), but not so much for the blended portions.

Given above, this only seems scalable if we were talking about a non-blended version of the component.

Maybe you had something else in mind?

**Comment by dipeshparashar** [comment]
So, speaking from the point of view of my use-case. I don't see anyone completely exhausting the combinations by highlighting(blending) N number of tags. In my app, i use it to mention a certain portion of a given comment added by user to which they are specifically referring. In most cases it will be 2-3 highlights (blends) on one string.  In that scenario.  I see my above mentioned way to be completely practical. 

Which is basically the ability to add a className to the span or div tag which you are creating for blend. 

So, i do not see scalability as an issue here.

**Comment by smhaley** [comment]
While true for your particular use case the total number of classes would be small. For example, three tags `tagA`, `tagB`, `tagC`.
This would introduce the following classes: `tagA, tagB, tagC` then the blended classes `tagAtagA, tagAtagB, tagAtagC, tagBtagC, tagBtagB, and tagCtagC`.

So for a simple app with three total tags there are now a total of 9 different css classes to manage. 

Additionally, the updated data model you provided does not seem to provide a method to supply the blended class names into the component. 

With an app of just 10 tags the number would scale to about 65 possible classes for a user to manage.

Just to clarify, this problem is very simple if there were no blending of tags. By that I mean, the tags cannot overlap. One tag per highlighted span. But this component is `TextAnnotateBlend`, the feature is the blending of the two provided colors to construct overlapping tags. It is the feature of overlapping of two highlighted spans that creates the issue, as blends obtain their own `mark` tag under the hood and so would need their own class.

To make this more concrete:

```
[
  {
      "start": 24,
      "end": 41,
      "text": "blend annotations",
      "tag": "tagB",
      "color": "#42f5f5",
      "customClasses": "myCustomClassB",
    },
  {
      "start": 30,
      "end": 40,
      "text": "annotation",
      "tag": "tagA",
      "color": "#00ff00",
      "customClasses": "myCustomClassA",
    }
]
```

These two tags overlap (blend) at positions 30 through 40. This blended span would need a new class whereas it is neither exclusively `tagB` or `tagA`. It is the overlap of the two. The tag color will become the blend of the following two colors `#00ff00, #42f5f5`. A third class would be needed that is the intersection of `myCustomClassB AND myCustomClassA`.

Let's take a step back. What are you trying to accomplish exactly and how might a new feature enhance this package for users with 2 tags or 200 tags? 

Or are you not in need of blending at all, and instead need simple annotations (no overlapping)?

**Comment by dipeshparashar** [comment]
For my use-case, overlapping is not a primary need. Just need a way to add customClass on a blend. Maybe we can have flags. As the best way is to to let the user choose & make informed decisions themselves.

`allowOverlap: Boolean`

And considering your worry about the scalability. 
`maxBlends: Number
or 
limitBlends: Number
`

**Comment by smhaley** [comment]
Okay I understand now. I think there is a miscommunication on the language.

In the context of this library `react-text-annotate-blend` and its only current component `TextAnnotateBlend`:

`blend` refers exclusively to overlapping annotations (tags) such that the colors **blend** together.

"highlight", "tag", "mark" all refer to a simple tagging use case.

In other words, `blend` is not interchangeable with any of the following: "highlight", "tag", "mark".

As such flags are not reasonable as the name of the component, `TextAnnotateBlend`,  strongly indicates that blending is a feature inextricably linked to its usage. As blending is a hard feature the issues I brought up earlier are here to stay.

What you are asking for is a separate component, lets call it `TextAnnotate`, with a feature to add classNames to individual tags (highlights) that cannot overlap/blend.


Does this sound right?

If so I think I can add that feature as [the original library this was forked from](https://github.com/mcamac/react-text-annotate) appears to be no longer maintained as well as the code is buggy.

**Comment by dipeshparashar** [comment]
Yes. That sounds right.

**Comment by smhaley** [comment]
Alright cool. I'll take a look and get something working and tested in a few days.

**Comment by dipeshparashar** [comment]
Great.

**Comment by smhaley** [comment]
Been sidetracked with work and life. Finally had some time. Should have this released in the next day or two -- testing now.

**Comment by smhaley** [comment]
Just released v 1.1 with className support for tags in the `TextAnnotate` component.

**Comment by smhaley** [comment]
I am going to close this issue out. The docs are not yet updated. 

The className key within a tag works just like the color key. 

Like we discuessed in the thread, the blending component does not support `className`. instead you will use the new component: `TextAnnotate`
  
  
This is the full definition of a tag:
```
declare type Span = {
    start: number;
    end: number;
    text?: string;
    color?: string;
    tag?: string;
};
interface AnnotateTag extends Span {
    className?: string;
}
```

`TextAnnotate` expects any shape that is at least an `AnnotateTag`

Here are two examples with the new component:

https://github.com/smhaley/react-text-annotate-blend/blob/main/examples/interactive-annotate.tsx

https://github.com/smhaley/react-text-annotate-blend/blob/main/examples/minimum-annotate.tsx

**Comment by smhaley** [comment]
I am going to close this issue as the latest release fully resolves. Please open another if you need  more help getting started.
